config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout
  get '/users/retire' => 'users#retire', as: :user_retire

  resources :users, only: :destroy
  resources :events do
    resources :tickets, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :tickets, dependent: :destroy
  has_many :users, through: :tickets

  validates :name, length: { maximum: 50 }, presence: true
  validates :place, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :start_time_should_be_before_end_time

  def created_by?(user)
    return false unless user

    owner_id == user.id
  end

  private

  def start_time_should_be_before_end_time
    return unless start_time && end_time

    errors.add(:start_time, 'は終了時間よりも前に設定してください') if start_time >= end_time
  end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :comment, length: { maximum: 30 }, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  before_destroy :check_all_events_finished

  has_many :created_events, class_name: 'Event', foreign_key: :owner_id, dependent: :nullify
  has_many :tickets, dependent: :nullify
  has_many :events, through: :tickets, dependent: :nullify
  has_many :participating_events, through: :tickets, source: :event, dependent: :nullify

  def self.find_or_create_from_auth_hash(auth_hash)
    provider = auth_hash[:provider]
    uid = auth_hash[:uid]
    nickname = auth_hash[:info][:nickname]
    image_url = auth_hash[:info][:image]

    find_or_create_by(provider: provider, uid: uid) do |user|
      user.nickname = nickname
      user.image_url = image_url
    end
  end

  private

  def check_all_events_finished
    now = Time.zone.now
    errors[:base] << '公開中の未終了イベントが存在します。' if created_events.where(':now < end_time', now: now).exists?
    errors[:base] << '未終了の参加イベントが存在します。' if participating_events.where(':now < end_time', now: now).exists?
    throw(:abort) if errors.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def authenticate
    return if logged_in?
    redirect_to root_path, alert: 'ログインしてください'
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate, except: [:show, :index]

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: '作成しました'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @ticket = Ticket.new
    @tickets = @event.tickets.includes(:user).order(:created_at)
    @current_user_ticket = current_user&.tickets&.find_by(event_id: params[:id])
  end

  def index
    @events = Event.where('start_time > ?', Time.zone.now).order(:start_time)
  end

  def edit
    @event = current_user.created_events.find(params[:id])
  end

  def update
    @event = current_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  private

  def event_params
    params.require(:event).permit(:name, :place, :content, :start_time, :end_time)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(request.env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path, notice: 'ログインしました'
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate

  def create
    ticket = current_user.tickets.build do |t|
      t.event_id = params[:event_id]
      t.comment = params[:ticket][:comment]
    end

    if ticket.save
      flash[:notice] = 'このイベントに参加表明しました'
      head 201
    else
      render json: { messages: ticket.errors.full_messages }, status: 422
    end
  end

  def destroy
    ticket = current_user.tickets.find_by!(event_id: params[:event_id])
    ticket.destroy!
    redirect_to event_path(params[:event_id]), notice: 'このイベントの参加をキャンセルしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate

  def retire
  end

  def destroy
    if current_user.destroy
      reset_session
      redirect_to root_path, notice: '退会完了しました'
    else
      render :retire
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to events_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_for_twitter(user)
    "https://twitter.com/#{user.nickname}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<% now = Time.zone.now %>

<div class="display-4 mt-4 mb-2 pb-2">
  <h1>イベント情報編集</h1>
</div>

<%= form_with model: @event, local: true do |f| %>
  <% if @event.errors.any? %>
  <div class="alert alert-danger mt-4 mb-2 pb-2">
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :start_time %>
    <div>
      <%= f.datetime_select :start_time, { start_year: now.year, end_year: now.year + 1 }, { class: 'form-control bootstrap-date' } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :end_time %>
    <div>
      <%= f.datetime_select :end_time, { start_year: now.year, end_year: now.year + 1 }, { class: 'form-control bootstrap-date' } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', row: 10 %>
  </div>

  <%= f.submit '更新', class: 'btn btn-secondary', data: { disable_with: '更新中…' } %>
<% end %>

app/views/events/index.html.erb
<div class="display-4 mt-4 mb-2 pb-2">
  <h1>イベント一覧</h1>
</div>

<ul class="list-group">
  <% @events.each do |event| %>
  <%= link_to(event, class: 'list-group-item') do %>
    <h4 class="my-auto">
      <%= event.name %>
    </h4>
    <p class="my-auto">
      <%= event.start_time.strftime('%Y/%m/%d %H:%M') %> - <%= event.end_time.strftime('%Y/%m/%d %H:%M') %>
    </p>
  <% end %>
  <% end %>
</ul>

app/views/events/new.html.erb
<% now = Time.zone.now %>

<div class="display-4 mt-4 mb-2 pb-2">
  <h1>イベント作成</h1>
</div>

<%= form_with model: @event, local: true do |f| %>
  <% if @event.errors.any? %>
  <div class="alert alert-danger mt-4 mb-2 pb-2">
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :place %>
    <%= f.text_field :place, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :start_time %>
    <div>
      <%= f.datetime_select :start_time, { start_year: now.year, end_year: now.year + 1 }, { class: 'form-control bootstrap-date' } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :end_time %>
    <div>
      <%= f.datetime_select :end_time, { start_year: now.year, end_year: now.year + 1 }, { class: 'form-control bootstrap-date' } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', row: 10 %>
  </div>

  <%= f.submit '作成', class: 'btn btn-secondary', data: { disable_with: '作成中…' } %>
<% end %>

app/views/events/show.html.erb
<div class="display-4 mt-4 mb-2 pb-2">
  <h1><%= @event.name %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="card">
      <div class="card-header">主催者</div>
      <div class="card-body">
        <% if @event.owner %>
        <%= link_to(url_for_twitter(@event.owner)) do %>
          <%= image_tag @event.owner.image_url %>
          <%= "@#{@event.owner.nickname}" %>
        <% end %>
        <% else %>
        退会したユーザです
        <% end %>
      </div>
    </div>

    <div class="card mt-4 mb-2 pb-2">
      <div class="card-header">開催時間</div>
      <div class="card-body">
        <%= @event.start_time.strftime('%Y/%m/%d %H:%M') %> - <%= @event.end_time.strftime('%Y/%m/%d %H:%M') %>
      </div>
    </div>

    <div class="card mt-4 mb-2 pb-2">
      <div class="card-header">開催場所</div>
      <div class="card-body">
        <%= @event.place %>
      </div>
    </div>

    <div class="card mt-4 mb-2 pb-2">
      <div class="card-header">イベント内容</div>
      <div class="card-body">
        <%= @event.content %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <% if @event.created_by?(current_user) %>
    <%= link_to 'イベントを編集する', edit_event_path(@event), class: 'btn btn-info btn-lg btn-block' %>
    <%= link_to 'イベントを削除する', event_path(@event), class: 'btn btn-danger btn-lg btn-block', method: :delete, data: { confirm: '本当に削除しますか？' } %>
    <% end%>

    <% if logged_in? %>
      <% if @current_user_ticket %>
      <%= link_to '参加をキャンセルする', event_ticket_path(@event, @current_user_ticket), method: :delete, class: 'btn btn-warning btn-lg btn-block' %>
      <% else %>
      <button class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#createTicket">参加する</button>

      <div class="modal fade" id="createTicket" tabindex="-1" role="dialog" aria-labelledby="dialogHeader" area-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="dialogHeader">参加コメント</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <%= form_with model: [@event, @ticket], url: event_tickets_path(@event), id: 'new_ticket' do |f| %>
              <div class="modal-body">
                <%= f.text_field :comment, class: 'form-control' %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                <%= f.button '送信', class: 'btn btn-primary', data: { disable_with: '送信中…' } %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    <% else %>
    <button class="btn btn-light btn-lg btn-block" disabled="disabled">参加するにはログインしてください</button>
    <% end %>

    <hr>
    <div class="card">
      <div class="card-header">参加者</div>
      <div class="card-body">
        <ul class="list-unstyled">
        <% @tickets.each do |ticket| %>
        <li>
          <% if ticket.user %>
          <%= link_to(url_for_twitter(ticket.user)) do %>
            <%= image_tag ticket.user.image_url, width: 20, height: 20 %>
            <%= "@#{ticket.user.nickname}" %>
          <% end %>
          <%= ticket.comment %>
          <% else %>
          退会したユーザです
          <% end %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeEvents</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="navbar navbar-expand-lg navbar-light bg-light" role="navigation" >
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'AwesomeEvents', root_path, class: 'navbar-brand' %>
        </div>

        <button type="button" class="navbar-toggler ml-auto" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="Navbar">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'イベントを作る', new_event_path, class: 'nav-link' %>
            </li>
            <% if logged_in? %>
            <li class="nav-item">
              <%= link_to '退会', user_retire_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログアウト', logout_path, class: 'nav-link' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to 'Twitterでログイン', '/auth/twitter', class: 'nav-link' %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </header>

    <div class="container">
      <% if flash[:notice] %>
      <div class="alert alert-success mt-4 mb-2 pb-2">
        <%= flash[:notice] %>
      </div>
      <% end %>
      <% if flash[:alert] %>
      <div class="alert alert-danger mt-4 mb-2 pb-2">
        <%= flash[:alert] %>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/retire.html.erb
<div class="display-4 mt-4 mb-2 pb-2">
  <h1>退会の確認</h1>
</div>

<% if current_user.errors.any? %>
<div class="alert alert-danger mt-4 mb-2 pb-2">
  <ul>
    <% current_user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<p>退会した場合、ユーザに関するデータが全て削除されます。</p>
<p>ただし、以下の場合は退会できません。</p>
<ul>
  <li>公開中の未終了のイベントがある場合</li>
  <li>未終了の参加イベントがある場合</li>
</ul>

<hr>

<%= link_to '退会する', user_path(current_user), method: :delete, class: 'btn btn-danger' %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>